// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CapturedMouseEvent = { mouse: MouseEvent, axAttributes: Record<string, string> | null, };

export type GetMouseEventsResult = { events: Array<CapturedMouseEvent>, };

export type MouseEvent = { x: number, y: number, eventType: string, timeUtcMs: number, };

export type RpcErrorResult = { error: string, };

export type StatusResult = { status: string, };
