// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Intent subset: role, sub-role, descriptions, title, value, DOM metadata, and geometry.
 */
export type AxAttributes = { axRole?: string | null, axSubrole?: string | null, axRoleDescription?: string | null, axTitle?: string | null, axValue?: string | null, axDescription?: string | null, axLabel?: string | null, axHelp?: string | null, axPlaceholderValue?: string | null, axIdentifier?: string | null, axDomIdentifier?: string | null, axDomClassList?: string | null, boundingBox?: AxBoundingBox | null, 
/**
 * Whether this node is the user-confirmed target for the event.
 * Defaults to `true` for the hit target (`current`) at capture time.
 */
selected?: boolean | null, };

/**
 * Bounding box for an accessibility element (screen coordinates).
 */
export type AxBoundingBox = { x: number, y: number, width: number, height: number, };

/**
 * Snapshot at the hit-tested element: `current`, ancestors (immediate parent first, then up),
 * and up to two **child** snapshots.
 *
 * `children` are normally the hit element’s `AXChildren`. If the hit target is a leaf with no
 * children (typical for `AXStaticText`, buttons, etc.), we use the first two children of the
 * **immediate parent** instead so the array is often useful for context.
 */
export type AxSnapshot = { current: AxAttributes, parents: Array<AxAttributes>, children: Array<AxAttributes>, };

export type CapturedMouseEvent = { mouse: MouseEvent, 
/**
 * Hit target, ancestor chain, and first two `AXChildren` (intent fields only).
 */
axAttributes: AxSnapshot | null, };

export type GetMouseEventsResult = { events: Array<CapturedMouseEvent>, };

export type MouseEvent = { x: number, y: number, eventType: string, timeUtcMs: number, };

export type RpcErrorResult = { error: string, };

export type StatusResult = { status: string, };
